printWidth: 120
useTabs: true
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: false
jsxBracketSameLine: true

overrides:
  - files: '*.json'
    options:
      useTabs: false
      tabWidth: 2
